@startuml activityDiagram
!theme carbon-gray
top to bottom direction

' ---------------------
' General style
' ---------------------
skinparam backgroundColor #FFFFFF
skinparam defaultFontSize 16
skinparam shadowing false
skinparam linetype ortho
skinparam ArrowStyle none

' Rectangle style
skinparam rectangle {
  RoundCorner 25
  BorderColor #2C3E50
}

' Package style
skinparam package {
  BackgroundColor transparent
}

' Component style
skinparam component {
  BackgroundColor #F5F5F5
  BorderColor #2C3E50
  BorderThickness 0
  FontName "Inter"
  FontSize 16
  FontStyle normal
}

' Node style
skinparam node {
  BackgroundColor #F5F5F5
  BorderColor #2C3E50
  FontColor #2C3E50
  Roundcorner 0
}

' ---------------------
' Activity Diagram
' ---------------------
folder "1) States" as StatesBlock {
  file "a. Recipes" as Recipes
  file "b. Render" as Render

  Recipes -> Render #6BCB77
}

folder "6) Go to Render" as GoToRenderBlock {
  file "a. Go to Render" as GoToRender
}

folder "2) Setup" as SetupBlock {
  file "a. Filters" as SetupFilters
  file "b. Dropdowns" as SetupDropdowns
  file "c. SearchBar" as SetupSearchBar
  file "d. Results Counter" as SetupCounter
  file "e. Cards" as SetupCards
  file "f. URL State" as UpdateURLState
  
  SetupFilters -down-> SetupDropdowns
  SetupDropdowns -down-> SetupSearchBar
  SetupSearchBar -down-> SetupCounter
  SetupCounter -down-> SetupCards
  SetupCards -down-> UpdateURLState
}

folder "3) Interactions" as InteractionsBlock {
  file "a. Click on Filters" as FiltersInteraction
  file "b. Click on Dropdowns" as DropdownsInteraction
  file "c. Type on Search" as SearchInteraction
  
  FiltersInteraction -[hidden]-> DropdownsInteraction
  DropdownsInteraction -[hidden]-> SearchInteraction
}

folder "4) EventBus" as EventBusBlock {
  rectangle "Filters: stateChanged" as EBState #LightGreen
  rectangle "Dropdowns: itemToggled" as EBItem #LightBlue
  rectangle "Search: searchChanged" as EBSearch #LightSkyBlue

  EBState -[hidden]-> EBItem
  EBItem -[hidden]-> EBSearch
}

folder "5) Filters" as FiltersBlock {
  file "a. Apply All Filters" as ApplyAllFilters
  file "b. Filter By Field" as FilterByField
  file "c. Filter By Search" as FilterBySearch

  ApplyAllFilters -[hidden]-> FilterByField
  FilterByField -[hidden]-> FilterBySearch
  FilterByField -up-> ApplyAllFilters
  FilterBySearch -up-> FilterByField
  ApplyAllFilters -up-> GoToRender
}



' ---------------------
' StatesBlock -> Setup
' ---------------------
StatesBlock -[hidden]-> SetupBlock
Render -[hidden]-> SetupFilters
GoToRenderBlock -[hidden]-> FiltersBlock
Render -down-> SetupFilters #6BCB77

' ---------------------
' Setup -> User Interactions
' ---------------------
SetupFilters -> FiltersInteraction
SetupDropdowns -> DropdownsInteraction
SetupSearchBar -> SearchInteraction
' ---------------------
' EventsBlock -> Filters
' ---------------------
FiltersInteraction -> EBState
DropdownsInteraction -> EBItem
SearchInteraction -> EBSearch

' ---------------------
' Filters -> EventBus
' ---------------------
EBState -> ApplyAllFilters
EBItem -> FilterByField
EBSearch -> FilterBySearch

' ---------------------
' Filters -> Go to Render
' ---------------------
GoToRender -> Render

@enduml
