@startuml projectStructure
!theme carbon-gray
top to bottom direction
allowmixing

' ---------------------
' Style
' ---------------------
' General style
skinparam linetype ortho
skinparam backgroundColor #FFFFFF
skinparam defaultFontSize 16
skinparam shadowing false
skinparam ArrowStyle none

' Rectangle style
skinparam rectangle {
  RoundCorner 25
  BorderColor $PRIMARY_DARK
}

' Package style
skinparam package {
  BackgroundColor transparent
}

' Component style
skinparam component {
	BackgroundColor $GRAY_10
	BorderColor $PRIMARY_DARK
  BorderThickness 0
  FontName "Inter"
  FontSize 16
  FontStyle normal
}

' Node style
skinparam node {
	BackgroundColor $GRAY_10
	BorderColor $PRIMARY_DARK
	FontColor $PRIMARY_TEXT
	Roundcorner 0
}
  ' file "ResultsCounter"
  ' file "Header" as headerInteraction
  ' file "ScrollToTop" as scrollToTopInteraction
' ---------------------
' Structure
' ---------------------
LesPetitsPlats -[hidden]-> Initializers
LesPetitsPlats -left-> Initializers

' Decision node for conditional flow

node "Success" as Success #LightGreen
node "Error" as Error #Red

' LesPetitsPlats node
package "LesPetitsPlats" as LesPetitsPlats {
  node "initApp"
}

package "Initializers" as Initializers {
  folder "Setup" as Setup {
    file "Skeletons" as SkeletonsInitializer
    file "ScrollToTop" as ScrollToTopInitializer
    file "Coordinator" as CoordinatorInitializer
    SkeletonsInitializer -down-> ScrollToTopInitializer
    ScrollToTopInitializer -down-> CoordinatorInitializer
  }

  folder "Fetcher" as Fetcher {
    file "RecipeApi"
    file "Cache"
    file "Config"
    RecipeApi -down-> Cache
    Cache -down-> Config
  }
  Setup -> Fetcher

  folder "Recipes" as Recipes {
    file "Build"
    file "Results" as ResultsBlock
    rectangle "Results Match" as ResultsDecision #LightBlue
    Build -down-> ResultsBlock
    ResultsBlock -down-> ResultsDecision #LightBlue
    ResultsDecision -[#LightGreen]-> Success
    ResultsDecision -[#Red]-> Error
  }
  Fetcher -> Recipes
}

package "Managers" as managersBlock {
  folder "Search" {
    file "elements" as searchElements
    file "state" as searchState
    file "render" as searchRender
  }

  folder "Cards" {
    file "elements" as cardsElements
    file "state" as cardsState
    file "render" as cardsRender
  }

  folder "Dropdowns" {
    file "elements" as dropdownsElements
    file "state" as dropdownsState
    file "render" as dropdownsRender
  }

  folder "Filters" {
    file "elements" as filtersElements
    file "state" as filtersState
    file "render" as filtersRender
  }
}
Success -> managersBlock #LightGreen

package "User Interactions" as UserInteractions {
  file "Search" as searchingInteraction
  file "Dropdowns" as dropdownsInteraction
  file "Filters" as filtersInteraction
  searchingInteraction --> filtersInteraction
  dropdownsInteraction --> filtersInteraction
}
UserInteractions -> Error #Red : "Aucun résultat trouvé"
LesPetitsPlats -> Error #Red : "Erreur recuperation recettes"
managersBlock -> UserInteractions

@enduml
