@startuml projectStructure
!theme carbon-gray
top to bottom direction
skinparam linetype ortho

' ---------------------
' General style
' ---------------------
skinparam backgroundColor #FFFFFF
skinparam defaultFontSize 16
skinparam shadowing false
skinparam linetype ortho
skinparam ArrowStyle none

' Rectangle style
skinparam rectangle {
  RoundCorner 25
  BorderColor #2C3E50
}

' Package style
skinparam package {
  BackgroundColor transparent
}

' Component style
skinparam component {
  BackgroundColor #F5F5F5
  BorderColor #2C3E50
  BorderThickness 0
  FontName "Inter"
  FontSize 16
  FontStyle normal
}

' Node style
skinparam node {
  BackgroundColor #F5F5F5
  BorderColor #2C3E50
  FontColor #2C3E50
  Roundcorner 0
}

' ---------------------
' Application Structure
' ---------------------
node "LesPetitsPlats" as LesPetitsPlats {
  folder "App"
}

rectangle "EventBus" as EventBusBlock #LightBlue

package "Init" as InitBlock {
  package "Setup" as SetupBlock {
    file "Skeletons" as SkeletonsInit
    file "ScrollToTop" as ScrollToTopInit
    
    SkeletonsInit -down-> ScrollToTopInit
  }

  package "Fetcher" as FetcherBlock {
    file "RecipeApi" as RecipeApi
    file "Cache" as CacheFetcher
    file "Config" as ConfigFetcher
    
    RecipeApi -down-> CacheFetcher
    CacheFetcher -down-> ConfigFetcher
  }

  package "Recipes" as RecipesBlock {
    file "Build" as RecipesBuilder
    file "Results" as RecipesResults
    rectangle "Match ?" as MatchResults #LightBlue
    rectangle "Error" as Error #Red
    rectangle "Success" as Success #LightGreen
    
    RecipeApi -down-> RecipesBuilder
    RecipesBuilder -down-> RecipesResults
    RecipesResults -down-> MatchResults
    MatchResults -down-> Error
    MatchResults -right-> Success
  }
}
LesPetitsPlats -[hidden]-> InitBlock
LesPetitsPlats -down-> InitBlock

package "Interactions" as InteractionsBlock {
  file "Filters" as FiltersInteraction
  file "Dropdowns / Search" as SearchInteraction
  
  FiltersInteraction <-right-> SearchInteraction
}

package "Managers" as ManagersBlock {
  file "Filters" as FiltersManager
  file "Dropdowns / Search" as SearchManager
  FiltersManager <-right-> SearchManager
  
}

package "Rendering" as RenderingBlock {
  rectangle "Error" as RenderError #Red
  rectangle "Success" as RenderSuccess #LightGreen
  file "Dropdowns / Count / Cards / Filters" as RenderComponents
}

' ---------------------
' Layout helpers
' ---------------------
InitBlock -[hidden]-> InteractionsBlock
InitBlock -[hidden]-> EventBusBlock
Success -[hidden]-> ManagersBlock
InteractionsBlock -[hidden]-> EventBusBlock
EventBusBlock -[hidden]-> ManagersBlock
ManagersBlock -[hidden]-> RenderingBlock
RenderingBlock -[hidden]-> Error

' ---------------------
' Flow
' ---------------------
Success -right-> FiltersInteraction
FiltersInteraction -down-> EventBusBlock

EventBusBlock -down-> FiltersManager
FiltersManager -down-> RenderError
FiltersManager -down-> RenderSuccess
RenderSuccess -down-> RenderComponents

@enduml
