@startuml projectStructure
!theme carbon-gray
top to bottom direction
allowmixing

' ---------------------
' Style
' ---------------------
' General style
skinparam linetype ortho
skinparam backgroundColor #FFFFFF
skinparam defaultFontSize 16
skinparam shadowing false
skinparam ArrowStyle none

' Rectangle style
skinparam rectangle {
  RoundCorner 25
  BorderColor $PRIMARY_DARK
}

' Package style
skinparam package {
  BackgroundColor transparent
}

' Component style
skinparam component {
	BackgroundColor $GRAY_10
	BorderColor $PRIMARY_DARK
  BorderThickness 0
  FontName "Inter"
  FontSize 16
  FontStyle normal
}

' Node style
skinparam node {
	BackgroundColor $GRAY_10
	BorderColor $PRIMARY_DARK
	FontColor $PRIMARY_TEXT
	Roundcorner 0
}

' ---------------------
' Application Structure
' ---------------------
LesPetitsPlats -[hidden]-> Initializers
LesPetitsPlats -left-> Initializers

package "LesPetitsPlats" as LesPetitsPlats {
  node "initApp"
}

package "Initializers" as Initializers {
  folder "Setup" as Setup {
    file "Skeletons" as SkeletonsInitializer
    file "ScrollToTop" as ScrollToTopInitializer
    file "Coordinator" as CoordinatorInitializer

    SkeletonsInitializer -down-> ScrollToTopInitializer
    ScrollToTopInitializer -down-> CoordinatorInitializer
  }

  folder "Fetcher" as Fetcher {
    file "RecipeApi"
    file "Cache"
    file "Config"
    RecipeApi -down-> Cache
    Cache -down-> Config
  }

  Setup -> Fetcher

  folder "Recipes" as Recipes {
    file "Build"
    file "Results" as ResultsBlock
    rectangle "Results Match" as ResultsDecision #LightBlue

    Build -down-> ResultsBlock
    ResultsBlock -down-> ResultsDecision #LightBlue
  }

  Fetcher -> Recipes
}

package "Managers" as managersBlock {
  folder "Search" {
    file "elements" as searchElements
    file "state" as searchState
    file "render" as searchRender
  }

  folder "Cards" {
    file "elements" as cardsElements
    file "state" as cardsState
    file "render" as cardsRender
  }

  folder "Dropdowns" {
    file "elements" as dropdownsElements
    file "state" as dropdownsState
    file "render" as dropdownsRender
  }

  folder "Filters" {
    file "elements" as filtersElements
    file "state" as filtersState
    file "render" as filtersRender
  }
}


package "User Interactions" as UserInteractions {
  file "Filters" as filtersInteraction
  file "Search" as searchingInteraction
  file "Dropdowns" as dropdownsInteraction

  searchingInteraction --> filtersInteraction
  dropdownsInteraction --> filtersInteraction
}

package "Status" as Responses {
  rectangle "Success" as Success #LightGreen
  rectangle "Error" as Error #Red
  rectangle "No results" as NoResults #Red 
  rectangle "Data Loaded" as DataLoaded #LightGreen
  Error -[hidden]-> NoResults
  Success -[hidden]-> DataLoaded

  DataLoaded <--> Success #LightGreen
  NoResults <--> Error #Red
}

LesPetitsPlats -[hidden]-> Responses
ResultsDecision -[hidden]-> Responses
Responses -[hidden]-> UserInteractions
filtersInteraction -> NoResults #Red
ResultsDecision -> Success #LightGreen
ResultsDecision -> NoResults #Red
initApp --> Error #Red


filtersInteraction -> DataLoaded #LightGreen
DataLoaded -down-> managersBlock #LightGreen

@enduml
