@startuml activityDiagram
!theme carbon-gray
!include theme/structure-theme.puml

top to bottom direction

' ---------------------
' Application Activity Structure
' ---------------------
folder "1) States" as StatesBlock {
  file "a. Recipes" as Recipes
  file "b. Render" as Render

  Recipes -> Render #6BCB77
}

folder "6) Go to Render" as GoToRenderBlock {
  file "a. Go to Render" as GoToRender
}

folder "2) Setup" as SetupBlock {
  file "a. Filters" as SetupFilters
  file "b. Dropdowns" as SetupDropdowns
  file "c. SearchBar" as SetupSearchBar
  file "d. Results Counter" as SetupCounter
  file "e. Cards" as SetupCards
  file "f. URL State" as UpdateURLState
  
  SetupFilters -down-> SetupDropdowns
  SetupDropdowns -down-> SetupSearchBar
  SetupSearchBar -down-> SetupCounter
  SetupCounter -down-> SetupCards
  SetupCards -down-> UpdateURLState
}

folder "3) Interactions" as InteractionsBlock {
  file "a. Click on Filters" as FiltersInteraction
  file "b. Click on Dropdowns" as DropdownsInteraction
  file "c. Type on Search" as SearchInteraction
  
  FiltersInteraction -[hidden]-> DropdownsInteraction
  DropdownsInteraction -[hidden]-> SearchInteraction
}

folder "4) EventBus" as EventBusBlock {
  rectangle "Filters: stateChanged" as FiltersState #LightGreen
  rectangle "Dropdowns: itemToggled" as DropdownsState #LightBlue
  rectangle "Search: searchChanged" as SearchState #LightSkyBlue

  FiltersState -[hidden]-> DropdownsState
  DropdownsState -[hidden]-> SearchState
}

folder "5) Filters" as FiltersBlock {
  file "a. Apply All Filters" as ApplyAllFilters
  file "b. Filter By Field" as FilterByField
  file "c. Filter By Search" as FilterBySearch

  ApplyAllFilters -[hidden]-> FilterByField
  FilterByField -[hidden]-> FilterBySearch
  FilterByField -up-> ApplyAllFilters
  FilterBySearch -up-> FilterByField
  ApplyAllFilters -up-> GoToRender
}

' ---------------------
' StatesBlock -> SetupBlock
' ---------------------
StatesBlock -[hidden]-> SetupBlock
Render -[hidden]-> SetupFilters
GoToRenderBlock -[hidden]-> FiltersBlock
Render -down-> SetupFilters #6BCB77

' ---------------------
' Setup -> Interaction
' ---------------------
SetupFilters -> FiltersInteraction
SetupDropdowns -> DropdownsInteraction
SetupSearchBar -> SearchInteraction
' ---------------------
' Interaction -> EventBusBlock
' ---------------------
FiltersInteraction -> FiltersState
DropdownsInteraction -> DropdownsState
SearchInteraction -> SearchState

' ---------------------
' EventBusBlock -> FiltersBlock
' ---------------------
FiltersState -> ApplyAllFilters
DropdownsState -> FilterByField
SearchState -> FilterBySearch

' ---------------------
' Filters -> Go to Render
' ---------------------
GoToRender -> Render

@enduml
