@startuml projectStructure
!theme carbon-gray
!include theme/structure-theme.puml

top to bottom direction

' ---------------------
' Application Structure
' ---------------------
node "LesPetitsPlats" as LesPetitsPlats {
  folder "App"
}

rectangle "EventBus" as EventBusBlock #LightBlue

package "Init" as InitBlock {
  package "Setup" as SetupBlock {
    file "Skeletons" as SkeletonsInit
    file "ScrollToTop" as ScrollToTopInit
    
    SkeletonsInit -down-> ScrollToTopInit
  }

  package "Fetcher" as FetcherBlock {
    file "RecipeApi" as RecipeApi
    file "Cache" as CacheFetcher
    file "Config" as ConfigFetcher
    
    RecipeApi -down-> CacheFetcher
    CacheFetcher -down-> ConfigFetcher
  }

  package "Recipes" as RecipesBlock {
    file "Build" as RecipesBuilder
    file "Results" as RecipesResults
    rectangle "Match ?" as MatchResults #LightBlue
    rectangle "Error" as Error #Red
    rectangle "Success" as Success #LightGreen
    
    RecipeApi -down-> RecipesBuilder
    RecipesBuilder -down-> RecipesResults
    RecipesResults -down-> MatchResults
    MatchResults -down-> Error
    MatchResults -right-> Success
  }
}

package "Interactions" as InteractionsBlock {
  file "Filters" as FiltersInteraction
  file "Dropdowns / Search" as SearchInteraction
  
  FiltersInteraction <-right-> SearchInteraction
}

package "Managers" as ManagersBlock {
  file "Filters" as FiltersManager
  file "Dropdowns / Search" as SearchManager

  FiltersManager <-right-> SearchManager
}

package "Rendering" as RenderingBlock {
  rectangle "Error" as RenderError #Red
  rectangle "Success" as RenderSuccess #LightGreen
  file "Dropdowns / Count / Cards / Filters" as RenderComponents
}

' ---------------------
' Init -> Structural
' ---------------------
LesPetitsPlats -[hidden]-> InitBlock
LesPetitsPlats -down-> InitBlock
InitBlock -[hidden]-> InteractionsBlock
InitBlock -[hidden]-> EventBusBlock
Success -[hidden]-> ManagersBlock
InteractionsBlock -[hidden]-> EventBusBlock
EventBusBlock -[hidden]-> ManagersBlock
ManagersBlock -[hidden]-> RenderingBlock
RenderingBlock -[hidden]-> Error

' ---------------------
' RecipesBlock => Interactions
' ---------------------
Success -right-> FiltersInteraction
FiltersInteraction -down-> EventBusBlock

' -------------------------------------------------
' EventBusBlock => FiltersManager => RenderingBlock
' -------------------------------------------------
EventBusBlock -down-> FiltersManager
FiltersManager -down-> RenderError
FiltersManager -down-> RenderSuccess
RenderSuccess -down-> RenderComponents

@enduml
